name: first Wf with actions

on: [push]

jobs:
  uses-first-actions:
    runs-on: ubuntu-latest
    steps:
      - name: some Script
        run: |
          pwd
          ls
      - name: first js actions
        uses: actions/hello-world-javascript-action@v1.1
        id: greet
        with:
            who-to-greet: Zakaria
      - name: output
        run: echo "${{steps.greet.outputs.time}}"